/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decodificadoradn;

import javax.swing.JOptionPane;

/**
 *
 * @author erikssonherlo
 */
public class Analisis extends javax.swing.JFrame {
    public String Aux1;
    public String Aux2;
    /**
     * Creates new form Analisis
     */
    AnalizadorADN Analisis = new AnalizadorADN();
    public Analisis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Analizador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        TextoADN1 = new javax.swing.JTextField();
        TextoADN2 = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 2, 2));
        jLabel2.setText("Secuencia de ADN No. 2:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 230, 30));

        Analizador.setBackground(new java.awt.Color(43, 46, 46));
        Analizador.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Analizador.setForeground(new java.awt.Color(250, 250, 244));
        Analizador.setText("Realizar Analisis");
        Analizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalizadorActionPerformed(evt);
            }
        });
        getContentPane().add(Analizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, 40));

        jLabel3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 2, 2));
        jLabel3.setText("Secuencia de ADN No. 1:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 230, 30));

        Salir.setBackground(new java.awt.Color(43, 46, 46));
        Salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Salir.setForeground(new java.awt.Color(250, 250, 244));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 310, 40));

        TextoADN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoADN1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextoADN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 290, -1));

        TextoADN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoADN2ActionPerformed(evt);
            }
        });
        getContentPane().add(TextoADN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 290, -1));

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("Analizador ADN");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 53));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoadn.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(800, 467));
        Fondo.setMinimumSize(new java.awt.Dimension(800, 467));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1390, -80, 1970, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnalizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalizadorActionPerformed
        Aux1 = TextoADN1.getText();
        Aux2 = TextoADN2.getText();
        Analisis.Analizar(Aux1,Aux2);
        JOptionPane.showMessageDialog(null,"Posibles Patrones: \n"+Analisis.Patrones+"Resultado del Analisis del ADN: \n"+Analisis.Coincidencias);
        // TODO add your handling code here:
    }//GEN-LAST:event_AnalizadorActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void TextoADN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoADN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoADN2ActionPerformed

    private void TextoADN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoADN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoADN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analizador;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField TextoADN1;
    private javax.swing.JTextField TextoADN2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
