/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decodificadoradn;

import javax.swing.JOptionPane;

/**
 *
 * @author erikssonherlo
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Analizar = new javax.swing.JButton();
        Informacion = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Analizar.setBackground(new java.awt.Color(43, 46, 46));
        Analizar.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Analizar.setForeground(new java.awt.Color(250, 250, 244));
        Analizar.setText("Analizar ADN");
        Analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(Analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 310, 40));

        Informacion.setBackground(new java.awt.Color(43, 46, 46));
        Informacion.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Informacion.setForeground(new java.awt.Color(250, 250, 244));
        Informacion.setText("Ver Información del Estudiante");
        Informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionActionPerformed(evt);
            }
        });
        getContentPane().add(Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 310, 40));

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(1, 1, 1));
        Titulo.setText("Analizador ADN");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 53));

        Salir.setBackground(new java.awt.Color(43, 46, 46));
        Salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Salir.setForeground(new java.awt.Color(250, 250, 244));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 310, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoadn.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(800, 467));
        Fondo.setMinimumSize(new java.awt.Dimension(800, 467));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1390, -80, 1970, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalizarActionPerformed
        // TODO add your handling code here:
        Analisis Analizar = new Analisis();
        Analizar.setVisible(true);
        this.setVisible(false);

        }
        public static void main(String args[]) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Interfaz().setVisible(true);
                }
            });
    }//GEN-LAST:event_AnalizarActionPerformed

    private void InformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Información del Estudiante:\n"+"Nombre: Eriksson José Hernández López \n"+"Registro Academico: 201830459 \n");

    }//GEN-LAST:event_InformacionActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analizar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Informacion;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
